version: '3.8'

services:
  app1:
    image: docker-monitor/app_image:A
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app_1
    restart: always
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  app2:
    image: docker-monitor/app_image:B1
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app_2
    restart: always
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  monitor:
    image: docker-monitor/monitor_image:latest
    build:
      context: ./monitor
      dockerfile: Dockerfile
    container_name: monitor_container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: ["npm", "start"]
    restart: always
