version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app_container
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  monitor:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    container_name: monitor_container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: ["npm", "start"]
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - app
